### ISSUE TITLE
Hangs when connection to memcached fails

### ISSUE THREAD

**Issue by ewa-dwornikowska** [benjibc/mongoose-memcached#8]
When the memcached server is down (ECONNREFUSED) mongoose-memcached hangs instead of getting data from the database.

**Comment by chitty** [comment]
I tried to solve this issue, but found out that the problem comes from the memcached library that mongoose-memcached uses.

Here is the (not yet tested/merged) PR from the memcached library that should fix this issue: https://github.com/3rd-Eden/memcached/pull/199.

**Comment by carlosabbate** [comment]
This commit f45ee54 does not solve the issue. 

When the connection to memcached fails it hangs the process even if mongoDB is available, this will keep happening as long as the underlying problem is not fixed, which was reported in [3rd-Eden/memcached#199](https://github.com/3rd-Eden/memcached/pull/199).
